name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        go build ./...

    - name: Generate toml file
      run: |
        ./kataribe -generate

    - name: Test
      run: |
        go test ./...

    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ver=`echo $GITHUB_REF | sed "s@.*/@@"`

        mkdir releases
        for os in linux ; do
          for arch in 386 amd64 arm64 ; do
            echo Build for ${os}/${arch}
            GOOS="${os}" GOARCH="${arch}" go build ./...
            zip -q releases/kataribe-${ver}_${os}_${arch}.zip kataribe LICENSE README.md
            rm kataribe
          done
        done
        for os in darwin ; do
          for arch in amd64 arm64 ; do
            echo Build for ${os}/${arch}
            GOOS="${os}" GOARCH="${arch}" go build ./...
            zip -q releases/kataribe-${ver}_${os}_${arch}.zip kataribe LICENSE README.md
            rm kataribe
          done
        done
        for os in windows ; do
          for arch in 386 amd64 ; do
            echo Build for ${os}/${arch}
            GOOS="${os}" GOARCH="${arch}" go build ./...
            zip -q releases/kataribe-${ver}_${os}_${arch}.zip kataribe.exe LICENSE README.md
            rm kataribe.exe
          done
        done
        (
          cd releases
          sha1sum * > SHASUMS
        )

        go get -u github.com/tcnksm/ghr
        `go env GOPATH`/bin/ghr ${ver} releases/
